blank_issues_enabled: false
contact_links:
  - name: GitHub Actions Discussions
    url: https://github.com/orgs/community/discussions/categories/actions
    about: Please ask general GitHub Actions questions here.
  - name: Hugo Community Forum
    url: https://discourse.gohugo.io/
    about: Please ask questions about Hugo here.
  - name: GitHub Actions Documentation
    url: https://docs.github.com/en/actions
    about: GitHub Actions official documentation here.
