name: 'Dev Image CI'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-image-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make build
      - run: make cirun cmd="corepack npm ci"
      - run: make cirun cmd="corepack npm run format:check"
      - run: make cirun cmd="corepack npm run lint"
      - run: make cirun cmd="corepack npm run tsc"
      - run: make cirun cmd="corepack npm test"
