name: CI Setup

on:
  workflow_call:
    outputs:
      lib-artifact-name:
        description: "The name of the uploaded lib artifact"
        value: "lib"

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c483a2134b # v4.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: corepack enable
      - run: corepack install
      - run: corepack npm ci

      - name: Build bundled action
        run: corepack npm run build

      - name: Upload built lib as artifact
        uses: actions/upload-artifact@4cea3ca74a44f3319808383c39686809633ee353 # v4.6.1
        with:
          name: lib
          path: lib
          retention-days: 1

      - name: Verify no changes in lib/
        run: |
          if [ "$(git diff --name-only lib/ | wc -l)" -gt 0 ]; then
            echo "::error::The 'lib/' directory is out of date. Please run 'npm run build' and commit the changes."
            git diff lib/
            exit 1
          fi
