name: CI Testing

on:
  workflow_call:
    inputs:
      lib-artifact-name:
        required: true
        type: string

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: corepack enable
      - run: corepack install
      - run: corepack npm ci

      - name: Run lint
        run: corepack npm run lint

      - name: Run prettier
        run: corepack npm run format:check

  unit-test:
    name: Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: corepack enable
      - run: corepack install
      - run: corepack npm ci

      - name: Download built lib artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.lib-artifact-name }}
          path: lib

      - name: Run unit tests
        run: corepack npm test

      - name: Upload test coverage as artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ matrix.os }}
          path: coverage

      - if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v6

  smoke-test:
    name: Smoke Test (${{ matrix.os }}, ext=${{ matrix.extended }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'macos-latest'
          - 'windows-latest'
        extended: [true, false]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v6

      - name: Download built lib artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.lib-artifact-name }}
          path: lib

      - name: Cache Hugo
        uses: actions/cache@v5
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
            ${{ env.RUNNER_TEMP }}/hugo_cache
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/action.yml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Setup Hugo (Latest)
        uses: ./
        with:
          hugo-version: 'latest'
          extended: ${{ matrix.extended }}

      - name: Run hugo version
        run: hugo version
