name: CI Security

on:
  workflow_call:

jobs:
  sast:
    name: SAST (zizmor)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905e20b33c5284eb99778e874838644 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          inputs: |
            .github/workflows
            action.yml
          persona: auditor
          min-severity: medium

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905e20b33c5284eb99778e874838644 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@9e8d4766113f8b6540d99818815f91e1d039910a # v3.28.10
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@9e8d4766113f8b6540d99818815f91e1d039910a # v3.28.10

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@9e8d4766113f8b6540d99818815f91e1d039910a # v3.28.10

  dependency-review:
    name: Dependency Review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905e20b33c5284eb99778e874838644 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/dependency-review-action@3b1597514bc493504996929944be6c125740441d # v4.5.0
        with:
          comment-summary-in-pr: always
