name: Action Smoke and Compatibility

on:
  schedule:
    - cron: '13 13 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scheduled-smoke:
    if: github.event_name == 'schedule'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
        extended:
          - true
          - false
    steps:
      - uses: actions/checkout@v6

      - name: Setup Hugo
        uses: ./
        with:
          hugo-version: 'latest'
          extended: ${{ matrix.extended }}

      - name: Run hugo version
        run: echo "hugo_version=$(hugo version)" >> "${GITHUB_OUTPUT}"
        id: hugo_version

      - name: '${{ steps.hugo_version.outputs.hugo_version }}'
        run: echo '${{ steps.hugo_version.outputs.hugo_version }}'

  manual-compatibility:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'macos-latest'
          - 'windows-latest'
        hugo-version:
          - 'latest'
          - '0.61.0'
        extended:
          - true
          - false
    steps:
      - uses: actions/checkout@v6

      - name: Setup Hugo
        uses: ./
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: ${{ matrix.extended }}

      - name: Run hugo version
        run: echo "hugo_version=$(hugo version)" >> "${GITHUB_OUTPUT}"
        id: hugo_version

      - name: '${{ steps.hugo_version.outputs.hugo_version }}'
        run: echo '${{ steps.hugo_version.outputs.hugo_version }}'
