name: 'CI/CD Pipeline'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '15 13 * * *' # daily at 13:15
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml

  testing:
    needs: setup
    uses: ./.github/workflows/reusable-testing.yml
    with:
      lib-artifact-name: ${{ needs.setup.outputs.lib-artifact-name }}

  security:
    needs: setup
    uses: ./.github/workflows/reusable-security.yml

  validation:
    needs: setup
    uses: ./.github/workflows/reusable-validation.yml
